name: Build and Test

on:
  push:
  pull_request:

jobs:
  xcode15:
    runs-on: macos-13
    steps:
      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2.0'
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test
  xcode16:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test
  xcode26:
    runs-on: macos-15
    steps:
      - name: Select Xcode 26-beta
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 26-beta
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test
